baseURL: https://muv1.github.io/autumn
disableKinds:
- RSS
- sitemap
enableGitInfo: true
ignoreFiles:
- /content/.*\.[^m]
- /content/.*\.m[^d]
- /content/.*\.md.
markup:
   goldmark:
      extensions:
         linkify: false
params:
   themeColor: theme-base-08
publishDir: docs
title: Autumn
