baseURL: https://a8nj.github.io/autumn

disableKinds:
- RSS
- sitemap

markup:
   goldmark:
      extensions:
         linkify: false

publishDir: docs
title: Autumn

ignoreFiles:
- /cs$
- /d/a\.d$
- /dart/a\.dart$
- /go/a\.go$
- /js$
- /nim/a\.nim$
- /php/a\.php$
- /py$
- /rb$
- /rs$
