baseURL: https://a8nj.github.io/autumn

disableKinds:
- RSS
- sitemap

markup:
   goldmark:
      extensions:
         linkify: false

publishDir: docs
title: Autumn

watchFiles:
- /content/.*index\.md$
- /layouts/_default/.*\.html$
- /static/main.css$
