baseURL: https://a8nj.github.io/autumn

disableKinds:
- RSS
- sitemap

ignoreFiles:
- /a$

markup:
   goldmark:
      extensions:
         linkify: false

publishDir: docs
resourceDir: docs
title: Autumn
