# example 1
nim compile a.nim
# example 2
nim c a.nim
# example 3
nimble install june
# example 4
nimble install https://github.com/may/june
# example 5
nimble install https://github.com/may/june@#head
