'द U+0926 DEVANAGARI LETTER DA (Other_Letter)'
'न U+0928 DEVANAGARI LETTER NA (Other_Letter)'
'र U+0930 DEVANAGARI LETTER RA (Other_Letter)'
'👨‍🌾 Man Farmer'
'👨‍🍳 Man Cook'
'👨‍🎓 Man Student'
'👨‍🎤 Man Singer'
'👨‍🎨 Man Artist'
'👨‍🏫 Man Teacher'
'👨‍🏭 Man Factory Worker'
'👨‍💻 Man Technologist'
'👨‍💼 Man Office Worker'
'👨‍🔧 Man Mechanic'
'👨‍🔬 Man Scientist'
'👨‍🚀 Man Astronaut'
'👨‍🚒 Man Firefighter'
