[dependencies]
regex = ""
tera = { path = "../tera" }
zip = { git = "https://github.com/zip-rs/zip" }

[package]
name = "north"
version = "1.0.0"
edition = "2018"

[profile.release]
lto = true
panic = 'abort'
