// Code generated by 'go generate'; DO NOT EDIT.

package main

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modkernel32 = windows.NewLazySystemDLL("kernel32.dll")

	procGetBinaryTypeW = modkernel32.NewProc("GetBinaryTypeW")
)

func GetBinaryType(name string, binaryType *int) (err error) {
	var _p0 *uint16
	_p0, err = syscall.UTF16PtrFromString(name)
	if err != nil {
		return
	}
	return _GetBinaryType(_p0, binaryType)
}

func _GetBinaryType(name *uint16, binaryType *int) (err error) {
	r1, _, e1 := syscall.Syscall(procGetBinaryTypeW.Addr(), 2, uintptr(unsafe.Pointer(name)), uintptr(unsafe.Pointer(binaryType)), 0)
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}
